dj10/blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name = 'detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchiveView.as_view(), name = 'archives'),
    # url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name = 'archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name = 'category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.tag, name = 'tag'),
    url(r'^search/$', views.search, name = 'search'),
]

dj10/dj10/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

dj10/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.html import strip_tags

from ckeditor_uploader.fields import RichTextUploadingField

import markdown

class Category(models.Model):
    name = models.CharField(max_length= 100)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length= 100)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length= 70)
    # body = models.TextField()
    body = RichTextUploadingField(verbose_name= '正文')
    created_time = models.DateTimeField(auto_now_add= True)
    modified_time = models.DateTimeField(auto_now= True)
    excerpt = models.CharField(max_length= 200, blank= True)

    category = models.ForeignKey(Category, on_delete= models.CASCADE)
    tags = models.ManyToManyField(Tag, blank= True)
    author = models.ForeignKey(User, on_delete= models.CASCADE)

    views = models.PositiveIntegerField(default= 0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs= {'pk': self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.excerpt = strip_tags(md.convert(self.body))[:54]
        super(Post, self).save(*args, **kwargs)


    class Meta:
        ordering = ['-created_time',]

dj10/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.text import slugify
from django.db.models import Q

from .models import *

import markdown
from markdown.extensions.toc import TocExtension


def index(request):
    post_all = Post.objects.all().order_by('-created_time')
    tags = Tag.objects.all()
    paginator = Paginator(post_all,4)
    page = request.GET.get('page')
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except EmptyPage:
        post_list = paginator.page(paginator.num_pages)
    return render(request, 'blog/index.html',{
        'post_list': post_list,
        'tags': tags
    })

def detail(request, pk):
    post = get_object_or_404(Post, pk = pk)
    tags = Tag.objects.all()
    post.increase_views()
    md = markdown.Markdown(extensions = [
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      # 'markdown.extensions.toc',
                                     TocExtension(slugify = slugify)
                                  ])
    post.body = md.convert(post.body)
    post.toc = md.toc
    return render(request, 'blog/detail.html', {'post': post, 'tags': tags})

def archives(request, year, month):
    post_list = Post.objects.filter(created_time__year= year,
                                    created_time__month= month
                                    ).order_by('-created_time')
    return render(request, 'blog/index.html', {'post_list': post_list})

def category(request, pk):
    cate = get_object_or_404(Category, pk = pk)
    tags = Tag.objects.all()
    post_list = Post.objects.filter(category = cate).order_by('-created_time')
    return render(request, 'blog/index.html', {'post_list': post_list, 'tags': tags})

def tag(request, pk):
    tag = get_object_or_404(Tag, pk = pk)
    tags = Tag.objects.all()
    post_list = Post.objects.filter(tags= tag)
    return render(request, 'blog/index.html', {'post_list': post_list, 'tags': tags})

def search(request):
    q = request.GET.get('q')
    error_msg = ''
    if not q:
        error_msg = "请输入关键词"
        return render(request, 'blog/index.html',{'error_msg': error_msg})
    post_list = Post.objects.filter(Q(title__icontains= q) | Q(body__icontains= q))
    return render(request, 'blog/index.html', {'error_msg': error_msg,'post_list': post_list})

class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

class CategoryView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk = self.kwargs.get('pk'))
        return super(CategoryView,self).get_queryset().filter(category= cate)

class ArchiveView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchiveView, self).get_queryset().filter(created_time__year = year, created_time__month = month)

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request,*args, **kwargs):
        response = super(PostDetailView,self).get(request, *args,**kwargs)
        self.object.increase_views()
        return response

dj10/templates/base.html
{% load staticfiles %}
{% load blog_tags %}

<!DOCTYPE html>
<html>
<head>
    <title>Dick &amp; JZW</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
    <link rel="stylesheet" href="{% static 'css/prism.css' %}">
    <link rel="stylesheet" href="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}">

    <!-- js -->
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'blog:index' %}">Dick & JZW</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          {% get_the_most_category as the_most %}
          {% for cate in the_most %}
              {% if forloop.first %}
                <li class="active"><a href="{% url 'blog:category' cate.pk %}">{{ cate.name }} <span class="sr-only">(current)</span></a></li>
                  {% else %}
                  <li><a href="{% url 'blog:category' cate.pk %}">{{ cate.name }}</a></li>
              {% endif %}
          {% endfor %}



{#        <li><a href="#">Linux</a></li>#}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">分类 <span class="caret"></span></a>
            {% get_categories as cate %}
          <ul class="dropdown-menu">
              {% for c in cate %}
                <li><a href="{% url 'blog:category' c.pk %}">{{ c.name }}</a></li>
              {% endfor %}

{#            <li><a href="#">Action</a></li>#}
{#            <li><a href="#">Another action</a></li>#}
{#            <li><a href="#">Something else here</a></li>#}
{#            <li role="separator" class="divider"></li>#}
{#            <li><a href="#">Separated link</a></li>#}
{#            <li role="separator" class="divider"></li>#}
{#            <li><a href="#">One more separated link</a></li>#}
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-right" method="get" action="{% url 'blog:search' %}">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="关键词" name="q">
        </div>
        <button type="submit" class="btn btn-default">Go</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</div>
{#<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>#}
{#<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>#}


<div class="container" style="margin-top: 60px;">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                
                {% endblock %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                
                {% endblock %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最近发表文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                            <li>
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </li>
                        {% endfor %}

                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                            <li>
                                <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                            </li>
                        {% endfor %}

                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                            <li>
                                <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span class="post-count">({{ category.post_set.count }})</span></a>
                            </li>
                        {% endfor %}

                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% for tag in tags %}
                            <li>
                                <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}({{ tag.post_set.count }})</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
{#                <div class="rss">#}
{#                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>#}
{#                </div>#}
            </aside>
        </div>
    </div>

<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2019
                    - <a href="http://www.jizhongwei.com/" title="网页模板" target="_blank">Dick的博客</a>
                </p>
            </div>
        </div>
    </div>
</footer>


<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

dj10/templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="glyphicon glyphicon-list"></span>{{ post.category }}
                <span class="glyphicon glyphicon-time"></span>{{ post.created_time }}
                <span class="glyphicon glyphicon-user"></span>{{ post.author }}
{#                                <span class="comments-link"><a href="#">4 评论</a></span>#}
                <span class="glyphicon glyphicon-eye-open"></span>{{ post.views }}
                <span class="glyphicon glyphicon-tags"></span>
                {% for tag in post.tags.all %}
                    {{ tag.name }}
                    {% if not forloop.last %}
                        |
                    {% endif %}
                {% endfor %}

{#                <span class="post-category"><a href="#">{{ post.category }}</a></span>#}
{#                <span class="post-date"><a href="#"><time class="entry-date"#}
{#                                                          datetime="2012-11-09T23:15:57+00:00">{{ post.created_time }}</time></a></span>#}
{#                <span class="post-author"><a href="#">{{ post.author }}</a></span>#}
{#                <span class="comments-link"><a href="#">4 评论</a></span>#}
{#                <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>#}
            </div>
        </header>
        <div class="entry-content clearfix">
            <p class="body">
                {{ post.body | safe }}
            </p>
        </div>
    </article>
{#    <section class="comment-area" id="comment-area">#}
{#                    <hr>#}
{#                    <h3>发表评论</h3>#}
{#                    <form action="#" method="post" class="comment-form">#}
{#                        <div class="row">#}
{#                            <div class="col-md-4">#}
{#                                <label for="id_name">名字：</label>#}
{#                                <input type="text" id="id_name" name="name" required>#}
{#                            </div>#}
{#                            <div class="col-md-4">#}
{#                                <label for="id_email">邮箱：</label>#}
{#                                <input type="email" id="id_email" name="email" required>#}
{#                            </div>#}
{#                            <div class="col-md-4">#}
{#                                <label for="id_url">网址：</label>#}
{#                                <input type="text" id="id_url" name="url">#}
{#                            </div>#}
{#                            <div class="col-md-12">#}
{#                                <label for="id_comment">评论：</label>#}
{#                                <textarea name="comment" id="id_comment" required></textarea>#}
{#                                <button type="submit" class="comment-btn">发表</button>#}
{#                            </div>#}
{#                        </div>    <!-- row -->#}
{#                    </form>#}
{#                    <div class="comment-list-panel">#}
{#                        <h3>评论列表，共 <span>4</span> 条评论</h3>#}
{#                        <ul class="comment-list list-unstyled">#}
{#                            <li class="comment-item">#}
{#                                <span class="nickname">追梦人物</span>#}
{#                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月12日 14:56</time>#}
{#                                <div class="text">#}
{#                                    文章观点又有道理又符合人性，这才是真正为了表达观点而写，不是为了迎合某某知名人士粉丝而写。我觉得如果琼瑶是前妻，生了三孩子后被一不知名的女人挖了墙角，我不信谁会说那个女人是追求真爱，说同情琼瑶骂小三的女人都是弱者。#}
{#                                </div>#}
{#                            </li>#}
{#                            <li class="comment-item">#}
{#                                <span class="nickname">zmrenwu</span>#}
{#                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月11日 23:56</time>#}
{#                                <div class="text">#}
{#                                    本能有可能会冲破格局，但格局有时候也会拘住本能。#}
{#                                </div>#}
{#                            </li>#}
{#                            <li class="comment-item">#}
{#                                <span class="nickname">蝙蝠侠</span>#}
{#                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月9日 8:56</time>#}
{#                                <div class="text">#}
{#                                    其实真理一般是属于沉默的大多数的。那些偏激的观点只能吸引那些同样偏激的人。前几年琼瑶告于妈抄袭，大家都表示大快人心，说明吃瓜观众都只是就事论事，并不是对琼瑶有偏见。#}
{#                                </div>#}
{#                            </li>#}
{#                            <li class="comment-item">#}
{#                                <span class="nickname">长江七号</span>#}
{#                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年2月12日 12:56</time>#}
{#                                <div class="text">#}
{#                                    观点我很喜欢！就是哎嘛本来一清二楚的，来个小三小四乱七八糟一团乱麻夹缠不清，简直麻烦要死#}
{#                                </div>#}
{#                            </li>#}
{#                        </ul>#}
{#                    </div>#}
{#                </section>#}
{% endblock %}

{% block toc %}
        <div class="widget widget-content">
            <h3 class="widget-title">文章目录</h3>
            {{ post.toc | safe }}
        </div>
{% endblock %}

dj10/templates/blog/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
                    <article class="post post-1">
                        <header class="entry-header">
                            <h1 class="entry-title">
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </h1>
                            <div class="entry-meta">
                                <span class="glyphicon glyphicon-list"></span>{{ post.category }}
                                <span class="glyphicon glyphicon-time"></span>{{ post.created_time }}
                                <span class="glyphicon glyphicon-user"></span>{{ post.author }}
{#                                <span class="comments-link"><a href="#">4 评论</a></span>#}
                                <span class="glyphicon glyphicon-eye-open"></span>{{ post.views }}
                                <span class="glyphicon glyphicon-tags"></span>
                                {% for tag in post.tags.all %}
                                    {{ tag.name }}
                                    {% if not forloop.last %}
                                        |
                                    {% endif %}
                                {% endfor %}


                            </div>
                        </header>
                        <div class="entry-content clearfix">
                            <p class="body">{{ post.excerpt }}...</p>
                            <div class="read-more cl-effect-14">
                                <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                            </div>
                        </div>
                    </article>
                {% endfor %}

                <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->
{#    <div class="pagination-simple">#}
{#        {% if post_list.has_previous %}#}
{#            <a href="?page={{ post_list.previous_page_number }}">Previus</a>#}
{#        {% endif %}#}
{#        <span class="current">第 {{ post_list.number }} 页 / 共 {{ post_list.paginator.num_pages }} 页</span>#}
{#        {% if post_list.has_next %}#}
{#            <a href="?page={{ post_list.next_page_number }}">Next</a>#}
{#          {% endif %}#}
{#    </div>#}

    <nav aria-label="...">
      <ul class="pager">
          {% if post_list.has_previous %}
              <li class="previous"><a href="?page={{ post_list.previous_page_number }}"><span aria-hidden="true">&larr;</span> Previus</a></li>
          {% endif %}
      {% if post_list.has_next %}
          <li class="next"><a href="?page={{ post_list.next_page_number }}">Next <span aria-hidden="true">&rarr;</span></a></li>
      {% endif %}
      </ul>
    </nav>
{% endblock %}

dj10/templates/blog/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .left {
            background-color: #337ab7;
            float: left;
            width: 200px;
        }
        .right {
            background-color: #e3e3e3;
            margin-left: 200px;
        }
    </style>
</head>
<body>
    <div class="left">left</div>
    <div class="right">right</div>
</body>
</html>